apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miapp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./environments/digital-ocean/miapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
